Precept 38
HJain01/Precept57 pull request #5
Opened 2022-06-22 01:53 UTC by Dallas-D

Beware the Mysterious Force ==> Fall Damage

And some minor README fixes

2022-06-30 23:55 UTC, jviszlai requested changes
Please fix commented bugs. Also your commit messages need more emojis ❤️

2022-06-30 23:55 UTC, jviszlai commented on Precept57/Precept57.cs
>              Precept35.Instance
missing comma

2022-06-30 23:55 UTC, jviszlai commented on Precept57/Precepts/Precept38.cs
> +            if (!Equipped()) return;
Equipped() no longer exists

2022-07-06 23:00 UTC, HJain01 approved these changes

2022-07-17 02:32 UTC, jviszlai approved these changes

2022-07-17 02:32 UTC, merged